import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'doodz',
  description: 'Generated by us',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
